### ISSUE TITLE
rocm-smi (rocm rel v.1.7) error

### ISSUE THREAD

**Issue by ekondis** [RadeonOpenCompute/ROC-smi#15] opened 2017-12-20 18:04 UTC
I've experienced the error below when I run rocm-smi with the just released rocm 1.7. Beyond this, opencl works fine.

```
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
Traceback (most recent call last):
  File "/opt/rocm/bin/rocm-smi", line 1056, in <module>
    showAllConcise(deviceList)
  File "/opt/rocm/bin/rocm-smi", line 706, in showAllConcise
    temp = getSysfsValue(device, 'temp')
  File "/opt/rocm/bin/rocm-smi", line 104, in getSysfsValue
    filePath = os.path.join(getHwmonFromDevice(device), pathDict['filepath'])
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

```

**Comment by gstoner** [comment] 2017-12-20 18:58
Did you Add your self to the video group  see the install instructions.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ekondis** [comment] 2017-12-20 19:48
Yes. I double checked via the "groups" command.

**Comment by ekondis** [comment] 2017-12-20 19:55
I think that the problem stems from the fact that the embedded Intel GPU is also active (I'm using it via a secondary windows installation on the same system for opencl). If I specify a particular AMD GPU device (-d) then I get no error.

**Comment by kentrussell** [comment] 2017-12-21 13:30
Yep that's on me. I fixed it on our master branch after we branched 1.7 but forgot to cherry pick the fix to the release branch. I will fix it shortly.

**Comment by kentrussell** [comment] 2017-12-21 13:53
It looks like my fix is in there, but your execution is missing that fix (your error is line 706, but should be 708, due to the 2-line fix that I added. Can you git log the rocm-smi and let me know the last commit?

**Comment by ekondis** [comment] 2017-12-21 18:06
I'm using rocm-smi as it comes from the ubuntu package repository (http://repo.radeon.com/rocm), not from the git repository. Thus, cannot do "git log".

**Comment by kentrussell** [comment] 2017-12-21 18:14
Looks like the package on the server is outdated. I will try to get them to update it accordingly

**Comment by kentrussell** [comment] 2017-12-21 20:02
The package should be updated in the next couple hours. Can you try it out again tonight or tomorrow?

**Comment by xMinox** [comment] 2017-12-21 20:14
I got similar prob when using latest git version:

```
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
  5   62.0c   90.226W  1200Mhz  2000Mhz  16.86%   manual    0%       
  3   70.0c   79.246W  1200Mhz  2000Mhz  16.86%   manual    0%       
  1   61.0c   92.254W  1200Mhz  2000Mhz  16.86%   manual    0%       
  8   55.0c   72.178W  1200Mhz  1950Mhz  16.86%   manual    0%       
  6   60.0c   76.115W  1200Mhz  2000Mhz  16.86%   manual    0%       
  4   51.0c   72.239W  1200Mhz  2000Mhz  16.86%   manual    0%       
  2   69.0c   73.219W  1200Mhz  2000Mhz  16.86%   manual    0%       
Traceback (most recent call last):
  File "./rocm-smi", line 1058, in <module>
    showAllConcise(deviceList)
  File "./rocm-smi", line 728, in showAllConcise
    fan = str(getFanSpeed(device))
  File "./rocm-smi", line 358, in getFanSpeed
    fanLevel = int(getSysfsValue(device, 'fan'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

TIA!

**Comment by kentrussell** [comment] 2017-12-21 20:17
Hmm, there may be a bigger issue with my rework than I thought. I liked the None data type but maybe I should have stuck with empty strings. What kind of gpus have you got in there,  xMinox?

**Comment by xMinox** [comment] 2017-12-21 20:20
9x Radeon RX570 but there is also an onboard Intel card

**Comment by kentrussell** [comment] 2017-12-21 20:26
Thanks. I did all my testing on AMD boards and Intel ones with the onboard disabled. Looks like o need to expand my test coverage. I will see what I can come up with.  It will be a personal branch since it is too late for an official release.

**Comment by xMinox** [comment] 2017-12-22 09:46
Great, thanks. Let me know if I can be of any help.

**Comment by kentrussell** [comment] 2017-12-22 15:25
Can you try out the new patch on the krussell/fixes branch and let me know if that fixes the issue? Having issues finding a machine like yours to test on with Christmas vacations abounding. Thanks!

**Comment by xMinox** [comment] 2017-12-22 15:45
Sure, no problem, here it is:

```
====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
  5   63.0c   70.167W  1200Mhz  2000Mhz  16.86%   manual    0%       
  3   70.0c   103.220W 1200Mhz  2000Mhz  16.86%   manual    0%       
  1   61.0c   70.243W  1200Mhz  2000Mhz  16.86%   manual    0%       
  8   55.0c   93.216W  1200Mhz  1950Mhz  16.86%   manual    0%       
  6   61.0c   76.95W   1200Mhz  2000Mhz  16.86%   manual    0%       
  4   50.0c   72.79W   1200Mhz  2000Mhz  16.86%   manual    0%       
  2   69.0c   74.151W  1200Mhz  2000Mhz  16.86%   manual    0%       
Traceback (most recent call last):
  File "./rocm-smi", line 1068, in <module>
    showAllConcise(deviceList)
  File "./rocm-smi", line 732, in showAllConcise
    fan = str(getFanSpeed(device))
  File "./rocm-smi", line 358, in getFanSpeed
    fanLevel = int(getSysfsValue(device, 'fan'))
ValueError: invalid literal for int() with base 10: ''

**Comment by kentrussell** [comment] 2017-12-22 17:53
Darn it. I missed that one. I got access to an Intel machine so I  will give that a shot later. Thanks xMinox!

**Comment by xMinox** [comment] 2017-12-22 21:56
No prob, let me know in case of anything. I can test it any time.

**Comment by antonioshadji** [comment] 2018-01-01 23:27
I'm having the same error.  Here results when run with version from krussell/fixes
GPU 1,2,3 are RX 570/580
GPU 0 is onboard intel i915.
I did not have this issue with 1.6 version.
my machine is ubuntu 16.04.3 with 4.13 Kernel and rocm-dkms installed. 

```
===================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
  3   50.0c   91.164W  1162Mhz  1750Mhz  80.0%    manual    0%       
  1   48.0c   89.168W  1145Mhz  2000Mhz  40.0%    manual    0%       
  2   43.0c   85.217W  1041Mhz  1750Mhz  40.0%    manual    0%       
Traceback (most recent call last):
  File "rocm-smi.py", line 1068, in <module>
    showAllConcise(deviceList)
  File "rocm-smi.py", line 732, in showAllConcise
    fan = str(getFanSpeed(device))
  File "rocm-smi.py", line 358, in getFanSpeed
    fanLevel = int(getSysfsValue(device, 'fan'))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by kentrussell** [comment] 2018-01-02 11:16
Thankfully it can still be run on the individual devices, but I know it's a pain. I'm going to redo how I handle returns from that function, and should have something up soon. Sorry for the inconvenience and delays...

**Comment by ghost** [comment] 2018-01-06 23:26
Same here what if limit it to amdgpu cards? or "known working cards"

vendor
/sys/class/drm/card1/device/vendor
0x1002

if vendor not in tuple/list continiue. at the top a list of working vendors
https://pci-ids.ucw.cz/read/PC/1002

btw i really like your tool, there is nothing similar arround. Great work!

**Comment by kentrussell** [comment] 2018-01-08 12:02
Thanks @derdigge and @AntoniosHadji  . It really just came down to me refactoring the whole thing for reusability from 1.6, but not testing it on all platform combinations (specifically an active Intel onboard GPU) and making some assumptions about what types of SysFS files would be present or missing. I've updated the krussell/fixes branch if you guys all want to give it a shot. If things are good, I'll try to see if we can update the repos to include this latest version. Thanks everyone for your patience and feedback!

**Comment by kentrussell** [comment] 2018-01-23 12:41
I have a fix for this being tested internally, and it should get pushed for 1.7.1. Thanks again everyone!

**Comment by nachitox** [comment] 2018-02-18 12:21
I found the same error

```
sudo ./rocm-smi 


====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD
Traceback (most recent call last):
  File "./rocm-smi", line 1058, in <module>
    showAllConcise(deviceList)
  File "./rocm-smi", line 728, in showAllConcise
    fan = str(getFanSpeed(device))
  File "./rocm-smi", line 358, in getFanSpeed
    fanLevel = int(getSysfsValue(device, 'fan'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

onboard intel graphics enabled
1 nvidia 1070
2 amd rx

**EDIT**
The problem is `return None` in getSysfsValue
To test, I changed it to `return '1'` and works

**Comment by gstoner** [comment] 2018-02-18 14:30
@nachitox @ekondis I am going to give you access to beta drop of 1.7.1  http://repo.radeon.com/misc/archive/beta/rocm-1.7.1-beta.tar.gz. that you can try out.

**Comment by antonioshadji** [comment] 2018-02-25 21:24
krussell/fixes branch works for me.  no errors on intel onboard chip.

**Comment by kentrussell** [comment] 2018-02-26 12:26
Thanks @AntoniosHadji . The next release will have these fixes, so it's nice to know that we're looking good thus far. Thanks for the confirmation!

**Comment by jasonacox** [comment] 2018-03-03 05:36
There is missing error handling for "None" type in some of the functions.  I added some minor handling for that. However, I believe the fundamental issue is with the listDevices() function.  It is not filtering out non-AMD GPUs.  I made a minor change to the listDevices() function to scan for AMD only devices based on Driver.  You can pull the change from my fork (https://github.com/jasonacox/ROC-smi) or I can submit a pull request.  Here is the change:

```python
def listDevices():
    """ Return a list of GPU devices.
          Revised: Restrict list to AMD devices only and return sorted.
    """
    devicelist = []
    deviceraw = [device for device in os.listdir(drmprefix) if re.match(r'^card\d+$', device)]
    for devicename in deviceraw:
        tempname = os.path.join(drmprefix, devicename, 'device/uevent')
        with open(tempname, 'r') as tempdetail:
           cardtype = tempdetail.readline().rstrip('\n')
           # print("GPU Found: %s - %s" % (devicename, cardtype))
           if cardtype in ['DRIVER=radeon', 'DRIVER=amdgpu']:
              devicelist.append(devicename)

    return sorted(devicelist)
```

**Comment by kentrussell** [comment] 2018-03-05 13:24
Can you try it out with the 1.7.1 release that just came out?

**Comment by kentrussell** [comment] 2018-03-05 13:39
And @jasonacox , there is one use-case issue where we have to return information about the CPU, since that is technically a node that KFD can use, so what you added might need a bit of massaging, but I'll try to get that implemented for our next release (and maybe do a Beta push to the krussell/fixes branch if I get it done soon enough). Thanks for your help!

**Comment by kentrussell** [comment] 2018-05-14 13:51
Assuming that it's fine since I haven't heard back in 2 months

**Closed as completed by kentrussell** 2018-05-14 13:51 UTC
