### ISSUE TITLE
The dmesg Trigger "DQM create queue failed" on rocm-smi by ROCm 1.8.192

### ISSUE THREAD

**Issue by heero-yuy** [RadeonOpenCompute/ROC-smi#38] opened 2018-08-21 08:05 UTC
Hi,

These days I found an issue about the consistly executing the rocm-smi by "watch -n 2 /opt/rocm/bin/rocm-smi" , the dmesg will report "DQM create queue failed" as screenshot attached, but the older version ROCm 1.8.1 didn't have this, may someone help to check what problem on ROCm-smi? Thanks!

![dqm_create_queue_failed](https://user-images.githubusercontent.com/32042214/44388916-02f53a00-a55c-11e8-9fb3-2473ccbee840.png)

**Comment by kentrussell** [comment] 2018-08-24 13:17
Considering you're running it every 2 seconds, you're generating 8 kernel queues to get the information (most of which aren't changing), and if there are too many queues created at once, they can't all be processed, since the kernel is also trying to run whatever you're running, which would result in those queues being unable to be created. Do you need to get all fields from the SMI, or only the temperature and power usage? If the latter, it would make more sense to just do a watch on those sysfs files instead.

If you use the latest SMI with the 1.7 kernel, does the issue persist? If so, it would be a kernel change, and not an SMI change.

Regardless, we can't guarantee results when you're using the SMI in a way that it was never intended to be used. It is not designed to be an efficient system monitor, it's designed to be a user-friendly way to take a snapshot look at the system information, and to make changes to power settings. For what you're looking for, a simple "watch -n 2 /sys/class/drm/card0/device/<whatever you're trying to monitor> would be sufficient.

**Comment by kentrussell** [comment] 2018-09-14 12:07
Closing since it's a kernel issue, and caused by a misuse of the tool

**Closed as completed by kentrussell** 2018-09-14 12:07 UTC

**Comment by heero-yuy** [comment] 2018-09-19 05:59
After checked that the ROCm 1.8.2 under ubuntu 16.04.5 with kernel version 4.15.0-34 hasn't triggered DQM Queues event, thanks!
