### ISSUE TITLE
`rocm-smi --setslevel` issue on Radeon VII

### ISSUE THREAD

**Issue by hairetikos** [RadeonOpenCompute/ROC-smi#65] opened 2019-05-01 00:53 UTC
trying to change voltage/clock of RVII by invoking:
rocm-smi --setslevel 1 1900 1118

throws this error:

Do you accept these terms? [y/N] y
Unable to write to to sysfs file /sys/class/drm/card0/device/pp_od_clk_voltage
WARNING: IO or OS error
GPU[0] 		: Unable to set sclk clock to Level s 1 1900 1118
WARNING: One or more commands failed
==============================End of ROCm SMI Log ==============================
root@amd:~# 

am I doing it right?

CentOS 7, latest amdgpu-pro, rocm-smi just for utility

**Comment by jlgreathouse** [comment] 2019-05-02 18:55
You likely do not have OverDrive enabled in your driver's ppfeaturemask.

**Comment by hairetikos** [comment] 2019-05-02 19:11
@jlgreathouse i already set `amdgpu.ppfeaturemask=0xffffffff`in the default kernel line and updated grub, so it must be something else

**Comment by jlgreathouse** [comment] 2019-05-02 19:33
Ah, I see, rocm-smi hasn't been updated with [the new `pp_od_clk_voltage` mechanism for Vega 20](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/roc-2.3.0/drivers/gpu/drm/amd/amdgpu/amdgpu_pm.c#L615). @kentrussell we should probably get a fix for this in the rocm-smi pipeline.

In particular, the old mechanism was to write `{CLOCK_TYPE -- s/m} {LEVEL} {CLOCK_FREQ} {VOLTAGE_POINT}` into `pp_od_clk_voltage`. However, with the move to Vega 20, we must now set clocks by:
 - Setting the max/min point by writing `{CLOCK_TYPE -- s/m} {LEVEL} {CLOCK_FREQ}` into `pp_od_clk_voltage`
 - Change the graphics clock voltage/frequency points that are part of a quadratic-fit line with `vc {LEVEL} {CLOCK_FREQ} {VOLTAGE_POINT}`

**Comment by jlgreathouse** [comment] 2019-05-02 19:34
@hairetikos 

You may want to look at that comment for the manual way to go about doing the voltage/frequency changes you want. Since `rocm-smi` is just a user-friendly frontend to all these sysfs writes, you should be able to do the changes you want manually while waiting for our fixes to make their way into a future `rocm-smi` release.

**Comment by hairetikos** [comment] 2019-05-02 19:51
@jlgreathouse thank you for the additional info, i will certainly take a look and use the manual sysfs method as i do with the powercap anyway

(cannot test yet, waiting on replacement RVII)

**Comment by hairetikos** [comment] 2019-05-10 14:39
@jlgreathouse i have tested using the sysfs directly, everything seems to work ok

i stumbled on this reddit post which is helpful for anyone else using the sysfs directly:  https://old.reddit.com/r/linux_gaming/comments/au7m3x/radeon_vii_on_linux_overclocking_undervolting/

thanks

**Comment by JMadgwick** [comment] 2019-07-29 17:16
I'm running ROCm 2.6 and this error still exists. Using sysfs directly works fine. The Radeon VII has been out for so long now that it's been discontinued! This could do with updating.

**Comment by kentrussell** [comment] 2019-08-01 14:23
@JMadgwick @hairetikos  I got stuck on a kernel bug for the last month+ so this got missed. I'm hoping to get it into 2.8. Thanks for bearing with us.

**Comment by hairetikos** [comment] 2019-08-01 22:04
@kentrussell ok, i still have Radeon VIIs for testing things

can confirm 2.6 still has the issue

**Comment by kentrussell** [comment] 2019-08-06 14:47
I'm working on this issue now. It will make it in for 2.8. Sorry for the delay, it's been hard reproducing it as I only have server cards and OverDrive is disabled natively for server cards, so trying to track down a consumer Vega20, combined with all of the other stuff I've been stuck on, has not been helpful. If I get a fix done quickly, I'll try push it to krussell/fixes so you can try it out.

**Comment by kentrussell** [comment] 2019-09-24 16:39
FINALLY fixed. I had to make 2 new flags for setting the voltage curve and clock points, but that will get around these issues . It will be in 2.9 (I missed the 2.8 cutoff)

**Comment by kentrussell** [comment] 2019-10-04 12:55
Please try out the new flags for setting voltage curve and clock points and let me know if it works for you.  Thanks again for your patience

**Closed as completed by kentrussell** 2019-10-04 12:55 UTC

**Comment by WannaBeOCer** [comment] 2019-10-09 04:08
@kentrussell I receive this error when trying to change the voltage.

```
Traceback (most recent call last):
  File "./rocm-smi", line 2765, in <module>
    setVoltageCurve(deviceList, args.setvc[0], args.setvc[1], args.setvc[2], args.autorespond)
  File "./rocm-smi", line 2161, in setVoltageCurve
    if int(point) > maxPoint:
TypeError: '>' not supported between instances of 'int' and 'str'
```

**Comment by kentrussell** [comment] 2019-10-09 11:44
You can get around it by putting int(maxPoint) instead of maxPoint there, but I will have a fix for this in 2.10

**Comment by JMadgwick** [comment] 2019-10-24 20:57
This error is not fixed. Are we still waiting for 2.10 to fix this? I am still getting the:
```
Unable to write to sysfs file /sys/class/drm/card0/device/pp_od_clk_voltage
WARNING: IO or OS error
ERROR: GPU[0] 		: Unable to set sclk clock to Level s 1 2101 1150
WARNING: One or more commands failed
```
Using `echo "vc 1 2101 1150" > /sys/class/drm/card0/device/pp_od_clk_voltage` works fine.

**Comment by kentrussell** [comment] 2019-10-25 11:55
The --setslevel is only going to work on Vega10. Instead of trying to if/else the --setslevel function based on the GPU, I added the --setvc and --setsrange/--setmrange to do the same functionality as the single --setslevel command, in the interests of convenience and future-proofing. Can you try those functions instead? I'll get the documentation updated to explicitly point this out.
